name: sunimtf
channels:
  - conda-forge
  - defaults
dependencies:
 - astropy
 - cudnn
 - matplotlib
 - numpy
 - opencv
 - pip
 - python=3.9 
 - reproject
 - scikit-image
 - scipy
 - sunpy
 - pip:
   - tensorflow
